name: CI
on:
  push:
    branches: master
  schedule:
  - cron: "0 0 1 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: kordianbruck/go-direct/server
        tags: latest
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true
